### ISSUE TITLE
Recovery priority problem

### ISSUE THREAD

**Issue by geranim0** [altf4/cpu-level-11#41]
Fox tries to do weird stuff with the current decision order. I moved the recovery options to the top of the decision order and the problems are gone.

**Comment by altf4** [comment]
Could you be more specific with the "weird stuff"? A video or gif of it would be best, but anything reproducible would be great too. Also, what exactly did you change? (A diff file would be great there)

**Comment by geranim0** [comment]
When offstage fox sometimes switch into the bait or edgeguard or shdl tactic instead of recovery. The bug is solved by moving the recovery options to the top of the decision tree. To reproduce the bug:
ledge stall with marth until fox rolls to marth killer, then ledge hop reverse nair and fsmash to edgeguard and the bug will happen.

**Comment by altf4** [comment]
Fixed in 8b1d52edcdd23bf5af288372da823bb6ab7a9399
